# Generated by Django 2.2.5 on 2020-08-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_peopleinfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='peopleinfo',
        ),
    ]
